openapi: 3.0.0
info:
  title: Stash FO api
  version: 1.0.0
  description: Stash FO api

servers:
  - url: http://localhost:8080

tags:
  - name: stash-controller
    description: Stash api controller

paths:
  /getStashDetail:
    get:
      tags:
        - stash-controller
      summary: API_STS_2001, Stash 상세 조회
      description: Stash 상세 조회
      operationId: getStashDetail
      parameters:
        - name: stashId
          in: query
          description: stash 아이디
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회성공
          content:
            application/json:
              schema:
                $ref: './dto/StashDTO.yaml#/components/schemas/StashDetailOutDTO'
        '400':
          description: Invalid status value

  /getStashList:
    get:
      tags:
        - stash-controller
      summary: API_STS_2002, Stash 목록 조회
      description: Stash 목록 조회
      operationId: getStashList
      responses:
        '200':
          description: 조회성공
          content:
            application/json:
              schema:
                $ref: './dto/StashDTO.yaml#/components/schemas/StashListDTO'
        '400':
          description: Invalid status value

  /createStash:
    post:
      tags:
        - stash-controller
      summary: API_STS_2003, Stash 생성
      description: Stash 생성
      operationId: createStash
      requestBody:
        content:
          application/json:
            schema:
              $ref: './dto/StashDTO.yaml#/components/schemas/CreateStashInDTO'
      responses:
        '200':
          description: 조회성공
          content:
            application/json:
              schema:
                $ref: './dto/StashDTO.yaml#/components/schemas/StashDetailOutDTO'
        '400':
          description: Invalid status value

  /updateStash:
    post:
      tags:
        - stash-controller
      summary: API_STS_2004, Stash 수정
      description: Stash 수정
      operationId: updateStash
      requestBody:
        content:
          application/json:
            schema:
              $ref: './dto/StashDTO.yaml#/components/schemas/UpdateStashInDTO'
      responses:
        '200':
          description: 수정성공
          content:
            application/json:
              schema:
                $ref: './dto/StashDTO.yaml#/components/schemas/StashDetailOutDTO'
        '400':
          description: Invalid status value

  /deleteStash:
    get:
      tags:
        - stash-controller
      summary: API_STS_2005, Stash 삭제
      description: Stash 삭제
      operationId: deleteStash
      parameters:
        - name: stashId
          in: query
          description: stash 아이디
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 삭제성공
        '400':
          description: Invalid status value

components:
  schemas:
    Stash:
      $ref: './entity/StashEntity.yaml#/components/schemas/Stash'